name: Build And Run Tests
on:
  pull_request:
    types:
      - synchronize
      - opened
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      runTests:
        description: 'Trigger integration tests'
        required: true
        default: 'yes'

env:
  DOTNET_VERSION: '9.0.0' # Define .NET version as a workflow-level variabl

jobs:
  build:
    name: Build the Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore src/UniLx.ApiService/UniLx.ApiService.csproj

    - name: Build the Application
      run: dotnet build src/UniLx.ApiService/UniLx.ApiService.csproj --configuration Release

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore src/UniLx.Tests/UniLx.Tests.csproj

    - name: Run Unit Tests
      run: dotnet test src/UniLx.Tests/UniLx.Tests.csproj --no-build --verbosity normal

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: src/UniLx.Tests/TestResults/