name: Main CI Workflow

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      runTests:
        description: 'Trigger integration tests'
        required: true
        default: 'yes'

jobs:
  build:
    name: Build Application
    uses: ./.github/workflows/build.yml
    with:
      dotnet_version: '9.0.x'

  test:
    name: Test Application
    needs: build
    uses: ./.github/workflows/unit-test.yml
    with:
      dotnet_version: '9.0.x'

  integration-tests:
    name: Integration Tests
    needs: 
      - build
      - test
    uses: ./.github/workflows/integration-tests.yml

  sonar-analysis:
    name: Sonar Analysis
    needs: 
      - build
      - test
      - integration-tests
    uses: ./.github/workflows/sonar-analysis.yml

