name: SonarQube Cloud

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: '.NET version to use'
        required: true
        type: string

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Install Sonar Scanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Run SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.sonar_token }}
      run: |
        dotnet sonarscanner begin \
          /k:"UniLx" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.login=${{ secrets.sonar_token }} \
          /d:sonar.cs.opencover.reportsPaths=TestResults/**/coverage.cobertura.xml
        dotnet build src/UniLx.ApiService/UniLx.ApiService.csproj
        dotnet sonarscanner end /d:sonar.login=${{ secrets.sonar_token }}